USER_ROLE__SUPER = 1
USER_ROLE__ADMIN = 2
USER_ROLE__USER = 3

GROUP_ID__SUPER = 1
GROUP_ID__ADMIN = 2
GROUP_ID__ALL = 3

PRIVILEGE_KNOW = 'know'
PRIVILEGE_READ = 'read'
PRIVILEGE_WRITE = 'write'

HTTP_BAD_REQUEST = 400
HTTP_FORBIDDEN = 403
HTTP_NOT_FOUND = 404
